version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: descubrimiento-db
    restart: always
    environment:
      POSTGRES_DB: runafoto_cuestionarios
      POSTGRES_USER: runafoto_user
      POSTGRES_PASSWORD: runafoto_secure_password_prod_2026
      TZ: America/Lima
    volumes:
      - postgres_descubrimiento_data_v10:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./seed_espacios_alumnos.sql:/docker-entrypoint-initdb.d/3-seed_espacios.sql
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.40'
    networks:
      - cuestionario_net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: descubrimiento-web
    restart: always
    ports:
      - '4321:4321'
    environment:
      - DATABASE_URL=postgresql://runafoto_user:runafoto_secure_password_prod_2026@db:5432/runafoto_cuestionarios
      - HOST=0.0.0.0
      - PORT=4321
      - ASTRO_DEV_BACKGROUND=false
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.40'
    depends_on:
      - db
    networks:
      - cuestionario_net
      - runafoto-edge

volumes:
  postgres_descubrimiento_data_v10:

networks:
  cuestionario_net:
    driver: bridge
  runafoto-edge:
    external: true
